repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.10
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
  - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.11.0'  # Use a recent stable version
  hooks:
  - id: mypy
    language: python
    types: [python]
    entry: env MYPYPATH=src mypy --config-file pyproject.toml src tests
    pass_filenames: false  # Prevent pre-commit from passing files as args
    additional_dependencies: [
        # Type Stubs
        "types-PyYAML>=6.0",
        "types-requests",
        # Core Dependencies (match pyproject.toml sections)
        "fastapi[standard]>=0.115.12",
        "pydantic>=2.11.3",
        "pydantic-ai[mcp]>=0.0.55",
        "openai>=1.0.0",
        "typer>=0.9.0",
        "rich>=13.5.0",
        "shellingham>=1.5.0",
        "uvicorn==0.29.0",
        "websockets==12.0.0",
        "mcp>=0.5.0",
        "python-dotenv>=1.1.0",
        "typing-extensions>=4.7.0",
        "logfire>=0.16.0",
        # Dev/Test Dependencies
        "ruff>=0.11.0",
        "mypy>=1.5.1", # mypy itself
        "tomli>=2.0.1; python_version < '3.11'", # Conditional dependency
        "pyyaml>=6.0.1",
        "promptfoo==0.1.0",
        "pytest>=8.0.0",
        "httpx>=0.24.1",
        "pytest-asyncio>=0.23.0",
        "pytest-cov>=4.1.0",
        # Project itself - necessary for mypy to find local modules
        ".",
    ]
    stages: [pre-push]
- repo: local
  hooks:
  - id: markdownlint-fix
    name: markdownlint (fix)
    entry: markdownlint --fix
    language: system
    files: \\.md$
    stages: [pre-commit] # Run on commit
