prompts:
  - id: chat
    label: Chat Prompt
    raw: |
      You are a helpful assistant. Please respond to the following message in a friendly and informative way:

      {{input}}

  - id: story
    label: Story Prompt
    raw: |
      You are a creative writing assistant. Generate a story idea with a title and premise based on the following input:

      {{input}}

      The story idea should be original, creative, and engaging. The title should be catchy and the premise should be concise but intriguing.

providers:
  - id: openai:gpt-4o
    config:
      headers:
        Authorization: "Bearer ${OPENAI_API_KEY}"

testCases:
  - description: Basic greeting
    vars:
      input: "Hello, how are you today?"
    assert:
      - type: llm-rubric
        value: "The response should be a polite greeting."
      - type: javascript
        value: "output.length > 10"

  - description: Story about space
    vars:
      input: "Write a story about space exploration"
    assert:
      - type: llm-rubric
        value: "The response should include a creative story idea with a title and premise related to space exploration."
      - type: javascript
        value: "output.includes('space') || output.includes('exploration') || output.includes('planet')"

sharing:
  enabled: false # set to true to enable sharing of results
