name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LOGFIRE_ENABLED: "false"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LOGFIRE_API_KEY: ${{ secrets.LOGFIRE_API_KEY }}
      LOGFIRE_PROJECT_ID: ${{ secrets.LOGFIRE_PROJECT_ID }}
      ENVIRONMENT: "test"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies with system flag
        run: |
          uv pip install --system -e ".[dev,test]"

      - name: Run linting
        run: |
          ruff check .
          ruff format --check .

      - name: Run mypy type checking
        run: |
          mypy src tests

      - name: Run tests with coverage
        run: |
          pytest --cov=minecraft_ai tests/
